<style>    
    section {
        margin-left: 80px;
        margin-top: 10px;
        display:block;
        font: 15px 'Titillium Web'; 
    }
    section_header {                   
        font: bold 20px 'Titillium Web';        
        color: #245496;   
        margin-left: 30px;
    }
    hr {
        color: black;
        background-color: black;
        height: 2px;
        width: 350px;
        margin-left: -5px;
    }
    img {
        float: left;
    }    
    ul li {
         list-style-image: url('/biz/public/image/utility/a-list-bullet-blue.png');       
    }
    left {
        float:left;
        margin-left: 30px;
        width:450px;
    }
    right {
        float:right;
        margin-left: 30px;
        width:450px;
    }
    iframe{ width:350px; height: 300px; overflow-x: hidden; overflow-y: scroll }
</style>

<left>
<img src="/biz/public/image/utility/icons/orders.png">
<section>
    <section_header><a href="/biz/user/order-history">ORDERS</a></section_header>
<hr>    
    <ul>
        <li>Check Order Status</li>
        <li>Create a New Order Based on a Previous Order</li>
        <li>Complete or Delete an Unfinished Order</li>
        <li>Update Billing and Shipping Info</li>
        <li>Update Payment Info</li>
    </ul>
</section>

<img src="/biz/public/image/utility/icons/products.png">
<section>
    <section_header><a href="/biz/product">PRODUCT</a></section_header>
    <hr>
    <ul>
        <li>View Product and Price List</li>
        <li>Get Product Information</li>
        <li>Add Products to Shopping Cart</li>
    </ul>
</section>

<img src="/biz/public/image/utility/icons/training.png">
<section>
    <section_header>TRAINING</section_header>
    <hr>
    <ul>    
        <li>Learn About Products</li>
        <li>Learn About Marketing Your Business</li>
        <li>Learn About Teeth Whitening</li>
        <li>Take Exam</li>
    </ul>
</section>


<img src="/biz/public/image/utility/icons/downloads.png">
<section>
    <section_header><a href="/biz/downloads">DOWNLOADS</a></section_header>
    <hr>
    <ul>
        <li>Download Marketing Materials</li>
        <li>Download Business Documents</li>
        <li>Download Product Information</li>
    </ul>
</section>

<img src="/biz/public/image/utility/icons/account.png">
<section>
    <section_header><a href="profile">ACCOUNT</a></section_header>
    <hr>
    <ul>
        <li>View Your Account Information</li>
        <li>Update/Edit Your Account Information</li>
        <li>Password Help</li>
    </ul>
</section>

</left>

<right>
    
    <img src="/biz/public/image/utility/icons/support.png">
    <section>
        <section_header>SUPPORT</section_header>
        <hr>
        <ul>
            <li><a href="/biz/support/contact">Contact Support</a></li>
            <li>Support FAQ</li>            
        </ul>
    </section>
    
    <img src="/biz/public/image/utility/icons/announcement.png">
    <section>
        
        <section_header>ANNOUNCEMENT</section_header>
        <hr>
        <iframe src="/biz/news">
        <img src="/biz/public/image/utility/inner-scroll-bar.png" style="float:right;">
        
        <!--img src="/biz/public/image/utility/icons/dentals.png">
        <section>American Men and women, age 18 and over, were surveyed in 2008 in a joint effot by the American Dental...Read More
        </section>
        
        <div class ="clear: both;">
        <img src="/biz/public/image/utility/icons/smile.png">
        <section>Sodium perborate is an ingredient used in teeth whitening gel primarily in countries that restrict the use of peroxide...Read More
        </section>
        <div class ="clear: both;">
        <img src="/biz/public/image/utility/icons/business.png">
        <section>American Men and women, age 18 and over, were surveyed in 2008 in a joint effot by the American Dental...Read More
            </iframe-->
        </section>
        
    </section>
</right>