<h3>Orders</h3>
<div>
    <b>Incomplete:</b> You have not finished placing this order. Select to complete or delete. <br>
    <b>Pending:</b> Something is holding up this order. Contact your representative to find out why.<br>
    <b>Shipped:</b> This order shipped. Select to view, or re-order.<br>
</div>
<script type="text/javascript">	
	$(document).ready(function(){		
            //Display Loading Image
            function Display_Load()
            {
                $("#loading").fadeIn(900,0);               
            }
            //Hide Loading Image
            function Hide_Load()
            {
                $("#loading").fadeOut('slow');
            };	
            Display_Load();	
            $("#data").load("order-history-data/page/1", Hide_Load());
       });
</script>
	
<div id="loading" align="center"></div>
<div id="data"></div>