<hr />
<br />
<div id="change" style="text-align: center; width: 80%; margin: 0 auto;">
    <div style="float: left; width: 100px; height: 80px;">
        <img src="/biz/public/image/utility/bw-smile-rectangle.png" alt="Beaming White" height="80px">
    </div>
    <div style="float: left; text-align: left; margin-left: 12px;">
        <strong>
            <font style="color: #0033a0; font-size:30px; font-family: helvetica, arial, sans-serif; font-weight: 300;">
                Thank you for registering with Beaming White! 
            </font>
        </strong>
        <br />
        A sales representative will be in contact with you.
        <br />
        <br />
    </div>
</div>
<div id="hidden" style="text-align: center; width: 80%; margin: 0 auto; display: none;">
    Taking you back to the Beaming White Business Portal.
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<hr />

<!-- Google Code for Other Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1062820964;
var google_conversion_language = "en";
var google_conversion_format = "1";
var google_conversion_color = "ffffff";
var google_conversion_label = "0hsDCMzchAMQ5Ljl-gM";
var google_conversion_value = 1.00;
var google_conversion_currency = "USD";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/1062820964/?value=1.00&amp;currency_code=USD&amp;label=0hsDCMzchAMQ5Ljl-gM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>



<script>    
$(document).ready(function() {
    setTimeout(function() {
        $("#change").fadeOut();
        //$("#change").replaceWith('<center><strong>Taking you back to the Beaming White Business Portal.</strong></center>');  
    }, 3200);
    setTimeout(function() {
        $("#hidden").fadeIn();    
    }, 3800);
    window.setTimeout(function(){
    window.location.href = "http://www.beamingwhite.com/business/";
    }, 4500);

 });
</script>
