<hr />
<head>
    <title>UK / EU Teeth Whitening Training</title>
    <style type="text/css">
    h4 {
        color: #000;
    }
    </style>
</head>
<h2>UK/EU Teeth Whitening Training</h2>
<p>Welcome to Beaming White's UK/EU online teeth whitening training. Below you will find 8 presentations that will help teach you how to be successful. You may take the exam at any time, but please do so once you have read through all the material and feel 100% confident in your knowledge. After the exam, an email containing the results of the exam will be sent to both you and your instructor.</p>

<h4>Training Materials</h4>
<ul>
    <li><a href='/biz/training/part1-lights'>Part 1: Lights</a></li>
    <li><a href='/biz/training/part2-gels'>Part 2: Gels</a></li>
    <li><a href='/biz/training/part3-legal'>Part 3: Legal</a></li>
    <li><a href='/biz/training/part4-safety'>Part 4: Safety</a></li>
    <li><a href='/biz/training/part5-staining'>Part 5: Staining</a></li>
    <li><a href='/biz/training/part6-expectations'>Part 6: Expectations</a></li>
    <li><a href='/biz/training/part7-how-teeth-whitening-works'>Part 7: How Teeth Whitening Works</a></li>
    <li><a href='/biz/training/part8-dental-conditions'>Part 8: Dental Conditions</a></li>
</ul>

<h4>Exam</h4>
<ul>
    <li><a href='/biz/training/pre-exam'>Take Exam</a></li>
</ul>
<hr />