<hr />
<a href="https://www.beamingwhite.com/biz/training/" title="Back to Training Materials"><< Back to Training Materials</a>
<a href="https://www.beamingwhite.com/biz/training/part4-safety" title="Continue to Part 4: Safety" style="float: right;">Continue to Part 4: Safety >></a>

<center>
    <h2>Part 3: Legal</h2>
    <iframe src="https://onedrive.live.com/embed?cid=84A870448A194BC2&resid=84A870448A194BC2%21112&authkey=ALWJxjDtRxJfDs4&em=2" width="502" height="427" frameborder="0" scrolling="no" style="margin-top: 10px;"></iframe>
</center>

<br />
<hr />
