<hr />
<a href="https://www.beamingwhite.com/biz/training/" title="Back to Training Materials"><< Back to Training Materials</a>
<a href="https://www.beamingwhite.com/biz/training/part2-gels" title="Continue to Part 2: Gels" style="float: right;">Continue to Part 2: Gels >></a>

<center>
    <h2>Part 1: Lights</h2>
    <iframe src="https://onedrive.live.com/embed?cid=84A870448A194BC2&resid=84A870448A194BC2%21113&authkey=AADsjPYASoGyOzE&em=2" width="502" height="427" frameborder="0" scrolling="no" style="margin-top: 10px;"></iframe>
</center>

<br />
<hr />