<hr />
<a href="https://www.beamingwhite.com/biz/training/" title="Back to Training Materials"><< Back to Training Materials</a>
<a href="https://www.beamingwhite.com/biz/training/part7-how-teeth-whitening-works" title="Continue to Part 7: How Teeth Whitening Works" style="float: right;">Continue to Part 7: How Teeth Whitening Works >></a>

<center>
    <h2>Part 6: Expectations</h2>
    <iframe src="https://onedrive.live.com/embed?cid=84A870448A194BC2&resid=84A870448A194BC2%21117&authkey=AEm77UvKS6aKb08&em=2" width="502" height="427" frameborder="0" scrolling="no" style="margin-top: 10px;"></iframe>
</center>

<br />
<hr />
