<hr />
<a href="https://www.beamingwhite.com/biz/training/" title="Back to Training Materials"><< Back to Training Materials</a>
<a href="https://www.beamingwhite.com/biz/training/part8-dental-conditions" title="Continue to Part 8: Dental Conditions" style="float: right;">Continue to Part 8: Dental Conditions >></a>

<center>
    <h2>Part 7: How Teeth Whitening Works</h2>
    <iframe src="https://onedrive.live.com/embed?cid=84A870448A194BC2&resid=84A870448A194BC2%21119&authkey=ADXXID9Z8CsT-wA&em=2" width="502" height="427" frameborder="0" scrolling="no" style="margin-top: 10px;"></iframe>
</center>

<br />
<hr />
