<!doctype html>
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<!--meta charset="utf-8"-->                
		<?php echo $this->headScript(); ?>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink(); ?>              
                <link href="/biz/public/css/biz.css" rel="stylesheet" type="text/css">
                <link href="/biz/public/js/ui-lightness/jquery-ui-1.10.2.custom.css" rel="stylesheet" type="text/css" />                
                <script type="text/javascript" src="/biz/public/js/jquery-1.10.2.min.js"></script>                
                <script type="text/javascript" src="/biz/public/js/jquery-ui-1.10.3.min.js"></script>
                
                <!--link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"-->
	</head>
        <?php echo $this->render('header.phtml'); ?>
        <body>            
             <? if(Zend_Auth::getInstance()->getIdentity() && Zend_Auth::getInstance()->getIdentity()->role !='customer'):?>             
              <?php echo $this->render('admin.phtml'); ?>
                <? elseif(Zend_Auth::getInstance()->getIdentity() && Zend_Auth::getInstance()->getIdentity()->role =='customer'):?>             
              <?php echo $this->render('customer.phtml'); ?>
            <?php endif;?>
   
            <div style="clear:both;"></div>
           
            <div id="container">       
                <?php echo $this->layout()->content; ?>
                <?php echo $this->inlineScript(); ?>            
            </div>
            <?php echo $this->render('footer.phtml'); ?>
	</body>         
</html>
 