<style>
table {
    border: none;
}
th, td {
    border: none;    
    padding-right: 3em;
    vertical-align: middle;
    text-align: center;
}
</style>
<h3>Downloads</h3>
<p>All files are copyright protected and may not be altered in any way. Files are for you use only while you are an active business customer of Beaming White. 
Select a category to find files to download. </p>
<table><tr><td><a href="/biz/downloads/file-lists/cat/business"><img src="/biz/public/image/utility/icons/business-downloads.png"></a></td>
        <td><a href="/biz/downloads/file-lists/cat/graphics"><img src="/biz/public/image/utility/icons/graphics-downloads.png"></a></td>
        <td><a href="/biz/downloads/file-lists/cat/marketing"><img src="/biz/public/image/utility/icons/marketing-material-downloads.png"></a></td>
        </tr>
        <tr><td><h4>BUSINESS DOCUMENTS</h4></td><td><h4>GRAPHICS FILES</h4></td><td><h4>MARKETING MATERIAL</h4></td></tr>
        <tr><td><a href="/biz/downloads/file-lists/cat/product"><img src="/biz/public/image/utility/icons/product-downloads.png"></a></td></tr>
        <tr><td><h4>PRODUCT INFORMATION</h4></td></tr>
</table>

