<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Ajax Upload and Resize with jQuery and PHP - Demo</title>
<script type="text/javascript" src="/biz/public/js/jquery/jquery.form.min.js"></script>
<link href="/biz/public/css/upload.css" rel="stylesheet" type="text/css" />

<script type="text/javascript">
$(document).ready(function() { 
	var options = { 
			target:   '#output',   // target element(s) to be updated with server response 
			beforeSubmit:  beforeSubmit,  // pre-submit callback 
			success:       afterSuccess,  // post-submit callback 
			resetForm: true        // reset the form after successful submit 
		}; 
		
	 $('#MyUploadForm').submit(function() { 
			$(this).ajaxSubmit(options);  			
			// always return false to prevent standard browser submit and page navigation 
			return false; 
		}); 
}); 

function afterSuccess()
{
	$('#submit-btn').show(); //hide submit button
	$('#loading-img').hide(); //hide submit button

}

//function to check file size before uploading.
function beforeSubmit(){
    //check whether browser fully supports all File API
   if (window.File && window.FileReader && window.FileList && window.Blob)
	{
		var error = '';
		if( !$('#imageInput').val()) //check empty input filed
		{
			//$("#output").html("Please select a file.");
                    error = "Please select a file.<br>";
		}
                if( !$('#category').val()) //check empty input filed
		{
			//$("#output").html("Please select a category.");
                    error = "Please select a category.<br>" + error;
		}
                if(!$('#caption').val()) //check empty input filed
		{			
		    error = "Please enter the caption field.<br>" + error;
		}
                if (error != '') {
                    $("#output").html(error);
                    return false;
                }
		
		var fsize = $('#imageInput')[0].files[0].size; //get file size
		var ftype = $('#imageInput')[0].files[0].type; // get file type
		

		//allow only valid image file types 
		switch(ftype)
        {
            case 'image/png': case 'image/gif': case 'image/jpeg': case 'image/pjpeg':
            case 'application/vnd.ms-excel': 
            case 'application/pdf': 
            case 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
            case 'application/vnd.openxmlformats-officedocument.wordprocessingml.document':               
                break;
            default:
                $("#output").html("<b>"+ftype+"</b> Unsupported file type!");
				return false
        }
		
		//Allowed file size is less than 1 MB (1048576)
		/*if(fsize>1048576) 
		{
			$("#output").html("<b>"+bytesToSize(fsize) +"</b> Too big Image file! <br />Please reduce the size of your photo using an image editor.");
			return false
		}*/
				
		$('#submit-btn').hide(); //hide submit button
		$('#loading-img').show(); //hide submit button
		$("#output").html("");  
	}
	else
	{
		//Output error to older unsupported browsers that doesn't support HTML5 File API
		$("#output").html("Please upgrade your browser, because your current browser lacks some new features we need!");
		return false;
	}
}

//function to format bites bit.ly/19yoIPO
function bytesToSize(bytes) {
   var sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
   if (bytes == 0) return '0 Bytes';
   var i = parseInt(Math.floor(Math.log(bytes) / Math.log(1024)));
   return Math.round(bytes / Math.pow(1024, i), 2) + ' ' + sizes[i];
}

</script>
<!--link href="style/style.css" rel="stylesheet" type="text/css"-->
</head>

<body>
<div id="upload-wrapper">
<div align="center">
    <h3>File Upload</h3>
    <form method="post" enctype="multipart/form-data" id="MyUploadForm">
        <table>
            <tr><td><input name="ImageFile" id="imageInput" type="file" /></td></tr><br>
            <tr><td>category: <select name="category" id="category" />  
                         <option value=""></option>
                        <?foreach ($this->categories as $key => $category) :?>
                            <option value="<?= $key?>"><?= $category?></option>
                        <?endforeach;?>
                     </select>
                </td>
            </tr>
            <tr><td>User Type:<select name="userType" id="userType" />
                        <option vlaue="All">All</option>
                        <option vlaue="Dentist">Dentist</option>
                        <option vlaue="Non-Dentist">Non-Dentist</option>                        
                    </select>
                </td></tr>
            <tr><td>Caption: <input name="caption" id="caption" type="text" /></td></tr>
        </table>
        
        <input type="submit" id="submit-btn" value="Upload" />
        <img src="/biz/public/image/utility/ajax-loader.gif" id="loading-img" style="display:none;" alt="Please Wait"/>
    </form>
    <div id="output"></div>
    </div>
</div>

</body>
</html>