<head>
    <!--link rel="stylesheet" type="text/css" href="/biz/public/js/jquery/easyui/themes/default/datagrid.css"-->
    <link rel="stylesheet" type="text/css" href="/biz/public/js/jquery/easyui/themes/default/easyui.css">
    <link rel="stylesheet" type="text/css" href="/biz/public/js/jquery/easyui/themes/icon.css">	      
    <script src="/biz/public/js/jquery.easyui.min.js"></script>    
</head>        

<?= $this->action('construction', 'production'); ?>
<div style="margin-bottom: 5px;"><h2>Unshipped Orders | Total: <?=$this->total ?></h2></div>
    
<table id="dg" title="Unshipped Orders" style="width:700px;height:auto"
			data-options="rownumbers:true,pagination:true,pageSize:20,
                        url:'get-unshipped-orders',method:'get'">	
	<thead>
            <tr>         
                <th data-options="field:'order_id',width:80,align:'center',sortable:'true'">Order ID</th>
                <th data-options="field:'payment_firstname',sortable:'true'">Customer Name</th>
                <th data-options="field:'order_status',sortable:'true', align:'center'">Order Status</th>    
                <th data-options="field:'total',align:'right',sortable:'true'">Order Total</th>
                <th data-options="field:'date_modified',sortable:'true'">Order Time</th>            
            </tr>
	</thead>
</table>
           
         <!--table class="easyui-datagrid" style="width:810px;height:auto">
         <thead>
            <tr>
            <th data-options="field:'action'">Action</th>
            <th data-options="field:'order_id',width:80,halign:'center'">Order ID</th>
            <th data-options="field:'accountName'">Customer Name</th>
            <th data-options="field:'leadStatus'">Order Status</th>    
            <th data-options="field:'total',align:'right'">Order Total</th>
            <th data-options="field:'email'">Order Time</th>            
            </tr>
        </thead>
        <tbody>
              <? foreach($this->orders as $order):?>    
                <tr><td><a href="/biz/crm/customer/id/<?=$order['order_id'] ?>">View</a> </td>      
                    <td data-options="width:80,halign:'center';"><?= $order['order_id']?></td>  
                    <td><?= $order["payment_firstname"];?> <?= $order["payment_lastname"];?></td>                           
                     <td><?= $order['order_status']?></td>
                    <td data-options="align:'right'">$<?= $order['total']?></td>
                     <td><?= $order['date_modified']?></td>
                    </tr>
                <? endforeach; ?>
        </tbody>
        </table>
    </div>
</div-->


<script type="text/javascript">
		$(function(){
			var pager = $('#dg').datagrid().datagrid('getPager');	// get the pager of datagrid
			pager.pagination({
				/*buttons:[{
					iconCls:'icon-search',
					handler:function(){
						alert('search');
					}
				},{
					iconCls:'icon-add',
					handler:function(){
						alert('add');
					}
				},{
					iconCls:'icon-edit',
					handler:function(){
						alert('edit');
					}
				}]*/
			});			
		})
	</script>