<style>    
    section {
        margin-left: 80px;
        margin-top: 10px;
        display:block;
        font: 15px 'Titillium Web'; 
    }
    section_header {                   
        font: bold 20px 'Titillium Web';        
        color: #245496;   
        margin-left: 30px;
    }
    hr {
        color: black;
        background-color: black;
        height: 2px;
        width: 350px;
        margin-left: -5px;
    }
    img {
        float: left;
    }    
    ul li {
        list-style-image: url('/biz/public/image/utility/a-list-bullet-blue.png');       
    }
    left {
        float:left;
        margin-left: 30px;
        width:450px;
    }
    right {
        float:right;
        margin-left: 30px;
        width:450px;
    }
</style>

<img src="/biz/public/image/utility/icons/dentals.png">
<section>American Men and women, age 18 and over, were surveyed in 2008 in a joint effot by the American Dental...Read More
</section>

<div class ="clear: both;">
    <img src="/biz/public/image/utility/icons/smile.png">
    <section>Sodium perborate is an ingredient used in teeth whitening gel primarily in countries that restrict the use of peroxide...Read More
    </section>
    <div class ="clear: both;">
    <img src="/biz/public/image/utility/icons/business.png">
    <section>American Men and women, age 18 and over, were surveyed in 2008 in a joint effot by the American Dental...Read More
    </section>