<head>     
     <link rel="stylesheet" type="text/css" href="/biz/public/css/tablesorter.css">	 
     <script type="text/javascript" charset="utf-8" src="/biz/public/js/table-sorter/jquery.tablesorter.min.js"></script>   
     <script type="text/javascript" charset="utf-8" src="/biz/public/js/table-sorter/jquery.tablesorter.widgets.min.js"></script>   
    
<style>
    .wrapper {
        position: relative;
        padding: 0 5px;
        height: 250px;
        overflow-y: auto;
    }
    .tablesorter, .tablesorter .tablesorter-filter {
        width: auto;
    }
    .tablesorter .tablesorter-filter-row td:nth-child(15n+1) .tablesorter-filter {
        width: 250px;
    }
</style>
<script>
$(function(){
   // $("table.tablesorter tbody tr:nth-child(even)").addClass("striped");   
        var options = {
    widthFixed : true,
    showProcessing: true,
    //headerTemplate : '{content} {icon}', // Add icon for jui theme; new in v2.7!
    headerTemplate : '{content}', // Add icon for jui theme; new in v2.7!
    //
    //widgets: [ 'uitheme', 'zebra', 'stickyHeaders', 'filter' ],
    widgets: ['stickyHeaders', 'filter' ],

    widgetOptions: {

      // extra class name added to the sticky header row
      stickyHeaders : '',
      // number or jquery selector targeting the position:fixed element
      stickyHeaders_offset : 0,
      // added to table ID, if it exists
      stickyHeaders_cloneId : '-sticky',
      // trigger "resize" event on headers
      stickyHeaders_addResizeEvent : true,
      // if false and a caption exist, it won't be included in the sticky header
      stickyHeaders_includeCaption : true,
      // The zIndex of the stickyHeaders, allows the user to adjust this to their needs
      stickyHeaders_zIndex : 2,
      // jQuery selector or object to attach sticky header to
      stickyHeaders_attachTo : null,
      // scroll table top into view after filtering
      stickyHeaders_filteredToTop: true,

      // adding zebra striping, using content and default styles - the ui css removes the background from default
      // even and odd class names included for this demo to allow switching themes
     // zebra   : ["ui-widget-content even", "ui-state-default odd"],
      // use uitheme widget to apply defauly jquery ui (jui) class names
      // see the uitheme demo for more details on how to change the class names
     // uitheme : 'jui'
    }
  };

  $("table").tablesorter(options);
   
});
</script>

</head>

<?= $this->action('construction', 'production'); ?>
<a href='/biz/inventory/view'>>>Inventory Orders</a>
<div style="margin-bottom: 5px;"><h2>Item Inventory</h2></div>    
        <table class="account tablesorter" border="0" cellspacing="0" cellpadding="0">
            <thead>
               <tr>
                <th class="header" style="width:25%;">Item</th> 
                <th class="header" style="width:15%;">Total Ordered</th>                
                <th class="header" style="width:15%;">Total Received</th>
                <th class="header" style="width:15%;">Total In Stock <br>(China)</th>    
                <th class="header" style="width:15%;">Total Shipped</th>               
               </tr>
           </thead>
           <tbody>               
                 <? foreach($this->inventory as $inventory):?>    
                       <tr>
                       <td style="width:25%;"><?= $inventory['item']?></td>                         
                       <td align="right"><?= $inventory['quantity_ordered']?></td> 
                       <td align="right"><?= $inventory['quantity_received']?></td> 
                       <td align="right"><?= $inventory['quantity_oh']?></td> 
                       <td align="right"><?= $inventory['total_shipped']?></td>                        
                       </tr>
                 <? endforeach; ?>
           </tbody>
        </table>
