<?= $this->action('construction', 'production'); ?>
<table width="800px">
    <thead><th>Order Date</th><th>Invoice #</th><th>Total Price</th><th>Order Status</th><th></th></thead>
    <tbody>    
        
    <? foreach ($this->orders as $order):?>    
    <tr><td align="center"><?= date('m/d/Y', strtotime($order['date_modified']))?></td> 
        <td align="center"><a href="/biz/order/invoice/<?= $order['order_id']?>" target="_blank"><?=$order['order_id']?></a></td>
        <td align="right">$<?= $order['total']?></td>
        <td align='center'><?= $order['order_status']?></td>       
        <td align='center'><a>SELECT</a></td>       
    </tr>
    <? endforeach; ?>
    </tbody>
</table>

<?if(!empty($this->orders)):?>
<?= $this->partial('user/_pagination.phtml', array('page'=>$this->page, 
                                                   'totalPages'=>$this->totalPages, 'url'=>"/biz/crm/order-history-data/id/{$order['user_id']}/page/"));?>
<?endif;?>