

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    
<head>	
	<!--link rel="stylesheet" type="text/css" href="http://www.jeasyui.com/easyui/themes/default/easyui.css">
	<link rel="stylesheet" type="text/css" href="http://www.jeasyui.com/easyui/themes/icon.css">
        <link rel="stylesheet" type="text/css" href="http://www.jeasyui.com/easyui/demo/demo.css">
	
	<script type="text/javascript" src="http://www.jeasyui.com/easyui/jquery.easyui.min.js"></script>
	<script type="text/javascript" src="http://www.jeasyui.com/easyui/jquery.edatagrid.js"></script-->
              
       
    <link rel="stylesheet" type="text/css" href="/biz/public/js/jquery/easyui/themes/default/easyui.css">
    <link rel="stylesheet" type="text/css" href="/biz/public/js/jquery/easyui/themes/icon.css">
    <link rel="stylesheet" type="text/css" href="/biz/public/css/crm.css">   
               
  
</head>

<body>    
    
    <script type="text/javascript" src="/biz/public/js/jquery.easyui.min.js"></script>
    <script type="text/javascript" src="/biz/public/js/jquery/jquery.edatagrid.js"></script> 
        
	<script type="text/javascript">
		$(function(){
			$('#dg').edatagrid({
				url: "/biz/crm/get-product/id/<?= $this->userId?>",
				saveUrl: '/biz/crm/save-price/id/<?= $this->userId?>',
				updateUrl: '/biz/crm/update-price/id/<?= $this->userId?>',
				destroyUrl: '/biz/crm/delete-price/'
			});
                      
		});
	</script>
	<div class="demo-info" style="margin-bottom:10px">
		<div class="demo-tip icon-tip">&nbsp;</div>
		<div>Double click the row to begin editing.</div>
	</div>
	
	<table id="dg" title="Customer Product" style="width:700px;height:auto"
			toolbar="#toolbar" pagination="true" idField="product_price_id"
			rownumbers="true" fitColumns="true" singleSelect="true">
		<thead>
			<tr>
				<th field="name" width="50" editor="{type:'validatebox',options:{required:true}}">Product</th>
				<th field="min" width="50" editor="{type:'validatebox',options:{min:1,precision:2}}">Min Qty</th>
				<th field="max" width="50" editor="{type:'validatebox',options:{required:true}}">Max Qty</th>
                                <th field="price" width="50" editor="{type:'validatebox',options:{required:true}}">Price</th>
				<th field="unit" width="50" editor="{type:'validatebox',options:{required:true}}">Unit</th>
                                <th field="unit_description" width="50" editor="{type:'validatebox',options:{required:true}}">Unit Description</th>
                                 
			</tr>
		</thead>
	</table>
	<div id="toolbar">
		<a href="#" class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="javascript:$('#dg').edatagrid('addRow')">New</a>
		<a href="#" class="easyui-linkbutton" iconCls="icon-remove" plain="true" onclick="javascript:$('#dg').edatagrid('destroyRow')">Remove</a>
		<a href="#" class="easyui-linkbutton" iconCls="icon-save" plain="true" onclick="javascript:$('#dg').edatagrid('saveRow')">Save</a>
		<a href="#" class="easyui-linkbutton" iconCls="icon-undo" plain="true" onclick="javascript:$('#dg').edatagrid('cancelRow')">Cancel</a>
	</div>
    
      
	
</body>
</html>
