  <? if (!empty($this->products)):?>
<table class="account" width="500px;">
    <thead><th>Product</th><th>Min Qty</th><th>Max Qty</th><th>Price</th><th>Unit</th><th>Unit Description</th>
    </thead>
<tbody>
  
    <? foreach ($this->products as $product):?>    
    <tr><td><?= $product['name']?></td>
        <td><?= $product['min']?></td>
        <td><?= $product['max']?></td>
        <td align="right"><?= $product['price']?></td>
        <td align="right"><?= $product['unit']?></td>
        <td align="right"><?= $product['unit_description']?></td>
    </tr>
<? endforeach; ?>
    </tbody>
</table>
<?else:?>
<p>No special price or product for this customer.</p>
    <?endif;?>
